version: '3.4'
services:
    php:
        build:
            context: docker/php
        container_name: ${APP_NAME}_php
        restart: unless-stopped
        tty: true
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - pgsql
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www
        networks:
            - network
    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME}_nginx
        restart: unless-stopped
        tty: true
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        working_dir: /var/www
        networks:
            - network
    pgsql:
        container_name: ${APP_NAME}_pgsql
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgsql-volume:/var/lib/postgresql/data
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    pgsql-volume:
        driver: local
